# Generated by Django 4.0.6 on 2022-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='translation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
